dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - clang++
      - cmake
      - libgtest-dev
    env:
      - MATRIX_EVAL="CC=clang && CXX=clang++"
     
script:
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - make VERBOSE=1 #cmake --build .
  - cmake --build . --target package

before_deploy: 
  - 'export _PROJECT_NAME="HW10L20-Threads"'
  - 'export _PACKAGE_NAME="bulkmt"'
  - 'export _PROJECT_VERSION=`grep -Eo "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" cmake/GetGitRevisionDescription/version.cpp`'

deploy:
  - provider: script
    skip_cleanup: true
    script:
    - '! curl -T ${_PACKAGE_NAME}-${_PROJECT_VERSION}-Linux.deb -uboydad:$BINTRAY_API_KEY "https://api.bintray.com/content/boydad/otus-cpp/${_PROJECT_NAME}/${_PROJECT_VERSION}/${_PROJECT_NAME}/${_PACKAGE_NAME}-${_PROJECT_VERSION}-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1" | grep -v success'
